# Neste arquivo, foram definidos os seguintes hooks:
#
# codespell — Para detectar erros de digitação. Realiza a verificação tanto no código backend quanto no frontend.
# ruff — O Ruff Linter é um linter Python extremamente rápido, projetado como um substituto direto para o Flake8 (e dezenas de plugins), isort, pydocstyle, pyupgrade, autoflake e mais. Ele verifica o código Python apenas no backend.
#  Mantenha o ruff como a ferramenta principal de linting. Ele é rápido e pode lidar com grande parte das verificações de estilo e de erro.
# ruff-format — O formatador Ruff é um formatador de código Python extremamente rápido, projetado para substituir o Black. Ele é usado apenas para código Python no backend.
# mypy — O Mypy é um verificador de tipos estático para Python que visa combinar os benefícios da tipagem dinâmica (ou "duck typing") com a tipagem estática. É usado apenas para código Python no backend.
# prettier — O Prettier é um formatador de código com suporte para TypeScript (e outras linguagens). É utilizado exclusivamente para formatação de código TypeScript no frontend.
# black para formatação de linha: Configure o black para ajustar automaticamente as quebras de linha e formatação geral.
# isort para ordenação avançada de imports: Embora o ruff possa corrigir a ordem dos imports, o isort permite um controle mais detalhado e é configurável para perfis como o black.

# git config --global core.autocrlf input
# pre-commit install
# pre-commit autoupdate
# pre-commit run --all-files
# git commit -am 'Corrigindo erros apontados pelo pre-commit' --no-verify
# pip install types-requests
#mypy --install-types
# Exclui todos os arquivos, excento dentro das pastas
#exclude: '^(?!(tests|migrations)/)'

repos:
  # Hooks padrão para verificações de arquivos e formatação básica
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=500"]

  # Verificação de ortografia com codespell
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        name: Spell Checker
#        files: ^(apps|djud|deploy|pre-commit-bin)/
        args: ["--ignore-words=pre-commit-bin/ignore-words.txt"]
        stages: [pre-commit]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.2
    hooks:
      - id: ruff
        name: Ruff Linter (backend)
        args: ["--fix"]
        # "--select=F401,F841" Remove automaticamente os imports (F401 e variáveis (F841) não utilizadas
#        files: ^(apps|djud|deploy|pre-commit-bin)/  # Aplica-se apenas ao diretório backend
        stages: [pre-commit]
      - id: ruff-format
        name: Ruff Formatter (backend)
#        files: ^(apps|djud|deploy|pre-commit-bin)/  # Aplica-se apenas ao diretório backend
        stages: [pre-commit]

  - repo: https://github.com/psf/black
    rev: 24.10.0  # versão do Black
    hooks:
      - id: black
        args: ["--line-length", "80"]
#        files: ^(apps|djud|deploy|pre-commit-bin)/  # Aplica-se apenas ao diretório backend
        stages: [pre-commit]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2  # ou a versão mais recente
    hooks:
      - id: isort
        args: ["--profile", "black"]
        stages: [pre-commit]

  # Verificação de tipos com Mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        name: Mypy Type Checker (backend)
        args: ["--explicit-package-bases", "--config-file=mypy.ini"]  # Caminho para o arquivo mypy.ini
        additional_dependencies:
          [
            pydantic==2.9.2,
          ]
#        files: ^(apps|djud|deploy|pre-commit-bin)/  # Aplica-se apenas ao diretório backend
        stages: [pre-commit]


  # Hooks locais para verificações e testes de projeto específicos
  - repo: local
    hooks:
      # Verificação de declarações de depuração (debug) no código
      - id: debug-statements
        name: Check project for debug imports
        entry: python pre-commit-bin/debug_statements.py
        types: [python]
        pass_filenames: true
        language: system

      # Verificação de declarações de print em arquivos específicos
      - id: prints
        name: Check project for prints in views, forms, models and tasks
        entry: python pre-commit-bin/print_statements.py
        types: [python]
        pass_filenames: true
        language: system

      - id: no-delete-in-trusted
        name: No Delete in Trusted Directory
        entry: "sh -c 'if git diff --cached --name-status | grep -E \"^D\\s+data/trusted/\"; then echo \"Erro: Exclusões na pasta data/trusted não são permitidas.\"; exit 1; fi'"
        language: system
        stages: [commit]

      # Linting de código Python com Pylint
      - id: pylint
        name: The Python code linter
        language: system
        entry: sh -c 'PYTHONPATH=. python pre-commit-bin/pylint.py --rcfile=.pylintrc '
        types: [python]
        pass_filenames: false
