version: "3.7"
services:
  superset:
    image: "apache/superset:${SUPERSET_VERSION}"
    container_name: superset_app
    command: ["bash", "/app/superset_home/entrypoint.sh"]
    tty: true
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - LOAD_EXAMPLES="${LOAD_EXAMPLES}"
      - SUPERSET_CONFIG_PATH=/app/superset_home/test_config.py
    volumes:
      - ./scripts/entrypoint.sh:/app/superset_home/entrypoint.sh
      - ./tests/superset_config.py:/app/superset_home/test_config.py
  postgres:
    image: postgres:14.1-alpine
    hostname: pg
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
